### ISSUE TITLE
Add a LICENSE please

### ISSUE THREAD

**Issue by amitu** [ajhager/raf#1]
:-)

I am considering using it for my http://github.com/amitu/rkit, and am waiting for a LICENSE.

**Comment by ajhager** [comment]
Fixed by 05df12a31491301928606f6af2e8e4d9b49bb4c7

**Comment by ajhager** [comment]
I would love any PRs for bug fixes or enhancement. Keeping an eye on rkit. Thanks!

**Comment by amitu** [comment]
Thanks a lot @ajhager :-)
